name: ubuntu

on:
  push:
  pull_request:

jobs:

  ubuntu:
    name: ubuntu
    runs-on: ubuntu-latest
    steps:

      - name: checkout
        uses: actions/checkout@v3

      - name: setup-ghc-wasm32-wasi
        run: |
          PREFIX=/tmp/.ghc-wasm32-wasi ./setup.sh
          /tmp/.ghc-wasm32-wasi/add_to_github_path.sh
